FROM node:20-alpine

WORKDIR /app

COPY . .

RUN npm i --production

RUN npm run build

# Expose the port the app will run on
EXPOSE 3000

# Start the React app using the start script (which runs a server)
CMD ["npm", "start"]