version: "3.9"
services:
  test-db:
    image: postgres:17-alpine
    container_name: test-db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432" # Use a different port to avoid conflicts