services:
  db:
    container_name: postgres-db
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD=$POSTGRES_AUTH_METHOD
      - POSTGRES_INITDB_ARGS=$POSTGRES_INIT_ARGS
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    networks:
      - passmanager
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - passmanager_data:/var/lib/postgresql/data
    restart: always
    command: -p $POSTGRES_PORT
    labels:
      - "traefik.enable=true"

  passmanager-api:
    container_name: passmanager-api
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    networks:
      - passmanager
    volumes:
      - /app/node_modules
      - ./certs:/app/certs
      - ./server/.env:/app/.env
    labels:
      - "traefik.enable=true"

  passmanager-frontend:
    container_name: passmanager-frontend
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - ./certs:/app/certs
      #- ./client/.env:/app/.env
    networks:
      - passmanager
    labels:
      - "traefik.enable=true"

volumes:
  passmanager_data:


networks:
  passmanager:
    external: true
    driver: bridge
