services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: always
    command: -p $POSTGRES_PORT

  api:
    depends_on:
      - db
    build: ./server
    environment:
      - NODE_ENV=$API_NODE_ENV
      - PORT=$API_PORT
      - PGHOST=db
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - API_GET_LIST_ENDPOINT = $API_GET_LIST_ENDPOINT
      - API_ADD_PASS_ENDPOINT = $API_ADD_PASS_ENDPOINT
      - API_UPDATE_PASS_ENDPOINT = $API_UPDATE_PASS_ENDPOINT
      - API_DELETE_PASS_ENDPOINT = $API_DELETE_PASS_ENDPOINT
      - API_LOGIN_CHALLENGE_ENDPOINT = $API_LOGIN_CHALLENGE_ENDPOINT
      - API_LOGIN_VERIFY_ENDPOINT = $API_LOGIN_VERIFY_ENDPOINT
      - API_REGISTER_ENDPOINT = $API_REGISTER_ENDPOINT
      - API_LOGOUT_ENDPOINT = $API_LOGOUT_ENDPOINT
      - JWT_SECRET=$JWT_SECRET
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - ./server:/app
      - /app/node_modules