entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  file:
    directory: "/etc/traefik/rules"
    watch: true
  docker:
    exposedByDefault: false

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/localhost.pem"
        keyFile: "/certs/localhost-key.pem"

api:
  dashboard: true
  insecure: true