FROM node:20-alpine
WORKDIR /app
# Copy package.json and package-lock.json first for better caching
COPY package*.json ./

# Install only production dependencies
RUN npm install --production

# Copy the rest of your application code
COPY . .

# Build TypeScript files
RUN npm run build

# Start the application
CMD ["node", "build/server.js"]